micronaut:
  application:
    name: openApiBug
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /api-docs/**

netty:
  default:
    allocator:
      max-order: 3
